### ISSUE TITLE
Baby meal services in London

### ISSUE THREAD

**Issue by iteles** [iteles/blw-baby#42]
I need to open one of these for Portugal too because I have a few bookmarked BUT:
we will be going to London for a week and will be in an empty kitchen.

I don't want to have to buy all the staples plus lots of other stuff (or take it all from Portugal) to cook A all his meals, so I'm keen to understand whether there is a _good_ and somewhat _accessible_ meal delivery service in London for babies/toddlers.

Our criteria is:
+ No added salt
+ No added sugar
+ Organic if possible
+ Appropriate for toddlers
+ Can purchase as a single week's worth of meals (maybe 6-8 meals)
+ Can be delivered either already made (but would have to be freezable), frozen or as ingredients for us to put together (like the https://www.hellofresh.co.uk/ model)

Of course hellofresh itself is an option, we would just pick meals that the whole family can eat if we omit certain ingredients 👍 

But I'm keen to know what's out there!

**Comment by iteles** [comment]
This came up in the ads when I searched for Hello Fresh on Google: https://thefamilyfoodco.com/

**Comment by Stephanymtr** [comment]
Mamamade 
https://mamamadefood.com/

This is their menu and everything is organic 👍 
https://mamamadefood.com/collections/our-collection
<img width="1351" alt="Screenshot 2022-09-08 at 15 31 44" src="https://user-images.githubusercontent.com/91985721/189149635-fde18c35-b1b4-48aa-a696-51c53e2d7af7.png">
As you can see above, they do have a little bit of salt/sugar. Each meal will have a nutrition label. Just like The Family Co, Mamamade also delivers their meals frozen. 
https://mamamadefood.com/collections/our-collection/products/beetroot-burger-mash
<img width="828" alt="Screenshot 2022-09-08 at 15 37 11" src="https://user-images.githubusercontent.com/91985721/189150880-11d2d978-422e-4805-8b04-cef9c5586a0f.png">

The only issue is that they offer 12 meals min within their bundle options. 
<img width="1338" alt="Screenshot 2022-09-08 at 15 42 10" src="https://user-images.githubusercontent.com/91985721/189152275-821b62f5-5053-4d49-b6e5-02fedf08f127.png">
<img width="1129" alt="Screenshot 2022-09-08 at 15 43 13" src="https://user-images.githubusercontent.com/91985721/189152409-aab09377-dbfe-4015-8aed-f7990e69c1b7.png">

**Comment by Stephanymtr** [comment]
Pot for Tots
https://potsfortots.co.uk/
<img width="1185" alt="Screenshot 2022-09-08 at 15 50 23" src="https://user-images.githubusercontent.com/91985721/189154439-efe66e2c-2184-4d38-8a3f-47da5e183a39.png">

Need to order 8 meals minimum
<img width="1204" alt="Screenshot 2022-09-08 at 15 53 23" src="https://user-images.githubusercontent.com/91985721/189154886-642ff5c5-e273-4075-8b2c-e887933b8e12.png">
There are loads of vegetable in every recipe and all the meat is free range and organic.

They don't seem to have AS MANY options as the other companies above, but it may not be an issue since this will be a one time purchase.
<img width="971" alt="Screenshot 2022-09-08 at 15 56 34" src="https://user-images.githubusercontent.com/91985721/189155920-bf96f15d-f078-4d38-ab96-737e67b3b4c6.png">
None of these companies seem to talk about salt/sugar, but looking at the meal labels there's very little salt/sugar.

**Comment by Stephanymtr** [comment]
Poppets Baby Food

https://poppetsbabyfood.co.uk/products/stage-3
<img width="1220" alt="Screenshot 2022-09-08 at 16 16 45" src="https://user-images.githubusercontent.com/91985721/189160350-7554aec2-ad26-471d-a839-6fe9f9cb7745.png">
This company is very fancy! 🥇 
Each box contains 6 different frozen meals 
They offer : fresh, organic and seasonal meals 
Also, no preservatives or pasteurisation on their meals
<img width="404" alt="Screenshot 2022-09-08 at 16 14 32" src="https://user-images.githubusercontent.com/91985721/189159950-87bdddf2-90ec-4fac-a2ab-8d8ea26d8dfd.png">
<img width="182" alt="Screenshot 2022-09-08 at 16 14 38" src="https://user-images.githubusercontent.com/91985721/189159967-6da59540-d812-47a0-bbdd-d1dc47febda6.png">

Nutritional Info:
https://poppetsbabyfood.co.uk/pages/nutritional-information

**Comment by Stephanymtr** [comment]
Little Dish 
https://www.littledish.co.uk/where-buy
<img width="1267" alt="Screenshot 2022-09-08 at 16 37 13" src="https://user-images.githubusercontent.com/91985721/189165026-1971874f-4cbc-4dce-b355-ee37cf023105.png">

This is a very interesting option as well. They work with retailers all across the UK, so we can pass by the store to grab a couple of meals before the ones you order online arrive... as plan B if necessary. 

<img width="1047" alt="Screenshot 2022-09-08 at 16 39 47" src="https://user-images.githubusercontent.com/91985721/189165481-425d9981-fc15-4d1f-9ad5-229c36cf0a5d.png">

No vegan meals 💔  but loads of healthy options
<img width="1335" alt="Screenshot 2022-09-08 at 16 40 52" src="https://user-images.githubusercontent.com/91985721/189165792-cd6dde9f-82b1-4243-8a2b-7958b74fa50f.png">

**Comment by Stephanymtr** [comment]
Little Eats
https://little-eats.com/aboutus/
They'll deliver portioned, organic ingredients for breakfast, lunch and dinner every day of the week.  It reminds me of Hello Fresh, but just for babies. Unfortunately, they can't be ordered as a one time purchase. It requires a subscription - most of the companies that deliver the ingredients instead of the prepared meals will not offer one-time purchases.

**Comment by iteles** [comment]
Sadly Omami are closed right now!
<img width="665" alt="image" src="https://user-images.githubusercontent.com/4185328/189670790-c603125a-6723-4c19-95b0-0ba7062758d7.png">

**Comment by iteles** [comment]
The Family Food Co is also preferably a no from me, they add salt and use quite a few processed ingredients: 
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/4185328/189671572-8719f648-6fc7-4ff0-a754-328c658328f6.png">

Similarly Pots for Tots includes added sugar in the ingredients:
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/4185328/189672707-03df7914-4c57-42c3-b288-388bcbd1d4a4.png">

**Comment by iteles** [comment]
Went with Lune & Wild who had a slightly more interesting variety (but still a lot of 'pies' which will be annoying for a kid who doesn't like mashed potato and we ended up with 2 mash potato dishes):
https://www.luneandwild.co.uk/

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/4185328/189696028-4214543f-e5fb-49c8-b893-88fd187176f2.png">


<img width="1659" alt="image" src="https://user-images.githubusercontent.com/4185328/189695928-c6a4d749-8359-42be-8f80-e29213dd83eb.png">


<img width="392" alt="image" src="https://user-images.githubusercontent.com/4185328/189695805-7a8966f4-3289-400d-bce2-4a40dad01518.png">

All organic ingredients, no added salt or sugar and delivered frozen.

My plan is to use the majority of these dishes as sides if A seems like he's not eating the vegetarian options and cook up some quick animal protein we buy at the supermarket _if_ necessary.

Should arrive Wednesday.

**Comment by iteles** [comment]
Alex enjoyed these for the most part. They were a huge stress relief for me as a parent. 

I occasionally get emails from them saying they're adding a new dish to their menu. 

Closing and we can refer back for reference.

**Comment by iteles** [comment]
He enjoyed these for the most part. They were a huge stress relief for me as a parent.

I occasionally get emails from them saying they're adding a new dish to their menu.

Closing and we can refer back for reference.
